### PR TITLE
Update readme with proper Markdown formatting

### PR DESCRIPTION
**Pull request by quassy**

### CODE REVIEW

**Comment by agronick** [comment]
Have you tried compiling it. Automake won't compile without a file called README.

**Comment by quassy** [comment]
Oh that is stupid, I haven't actually. [But apparently you can tell automake to ignore this.](http://stackoverflow.com/questions/15013672/use-autotools-with-readme-md)

**Comment by agronick** [comment]
Yeah, I found the same link. Nothing they said worked. Its very stupid. 
There is the option of making a symlink but I don't know if Github will 
handle that correctly and make it relative.

**Comment by agronick** [comment]
This needs changes in automake before it can be merged.

**Pull request closed without merging**
