### PR TITLE
Add ref parameter to TextIter

### PR DESCRIPTION
**Pull request by inizan-yannick**
latest Gtk use reference on TextIter

### CODE REVIEW

**Comment by quassy** [comment]
Will this be merged? Currently `make` seems to fail because of this.

**Comment by agronick** [comment]
What version of Elementary are you using? I know that this was changed in the newer versions of GTK. But even on Freya with the stock repos the version of libgtk-3-dev is 3.10.8. Theres a note about it in the INSTALL file. Either way its gonna be broken for some people. Probably need to find a way for it to apply a diff file depending of the version of libgtk-3-dev.

**Comment by agronick** [comment]
I just changed the code to remove the section that was causing issues. Its a little more expensive but it saves end users from editing code.

**Comment by quassy** [comment]
FYI: I am using elementary Freya but with the daily source instead of final, so some stuff might be more recent on my system.

**Comment by agronick** [comment]
Download the latest stuff and try building a clean build. It should work fine. I worked around all the code that used that function + more features. Click user names.

**Comment by quassy** [comment]
Works fine now (well except a bunch of notices that probaby were there before also).

**Pull request closed without merging**
