### PR TITLE
Use HeaderBar.subtitle() for server name

### PR DESCRIPTION
**Pull request by quassy**
Instead of putting the room and server name onto one line this commit puts the server name in the headerbar subtitle. Only problem right now is that in the server window the server name is displayed twice.

Some lines have been changed by Scratch which likes to remove trailing whitespace. Only the additions of various `toolbar.set_subtilte(...)` are actually significant changes.

### CODE REVIEW

**Comment by agronick** [comment]
Can you fix it to remove the channel from the main title, then do a find for set_title and put toolbar.set_subtilte("") wherever else it sets the title and I'll be able to merge it.

**Comment by agronick** [comment]
It only sets the title in main_window.vala

**Comment by agronick** [comment]
Actually I can do it if you want

**Comment by quassy** [comment]
> Can you fix it to remove the channel from the main title, then do a find for set_title and put toolbar.set_subtilte("") wherever else it sets the title and I'll be able to merge it.

I'm not sure I get what you mean. I have tried to set / unset the subtitle every time the title is set so the subtitle gets removed when you return to the Welcome tab for example. Also to unset the title I think it's better to use `set_subtitle(null)`.

**Comment by agronick** [comment]
I just committed a fix

**Comment by quassy** [comment]
Your commit seems to do something completely different :D

**Comment by quassy** [comment]
Here is what my changes were doing:

**Comment by agronick** [comment]
Thats what it should be doing
screenshot from 2015-07-06 02 18 17

**Comment by quassy** [comment]
Sorry, just checked out yours from `git` and it works as expected. A screenshot as proof (also to show that Relay works under Solus too)
relay

**Comment by agronick** [comment]
Check it out now. Theres a ton of new updates. I added a bunch of 
settings too.

**Pull request closed without merging**
